apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-helloworld-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-helloworld-app
  template:
    metadata:
      labels:
        app: my-helloworld-app
    spec:
      containers:
      - name: my-helloworld-app
        image:  hello-world:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
